# Generated by Django 3.2.5 on 2021-07-14 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=100)),
                ('Subtitle', models.CharField(max_length=100)),
                ('Description', models.CharField(max_length=1000)),
            ],
        ),
    ]
