# Generated by Django 3.2.5 on 2021-07-15 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_blog_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='created_at',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='blog',
            old_name='Description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='blog',
            old_name='Subtitle',
            new_name='subtitle',
        ),
        migrations.RenameField(
            model_name='blog',
            old_name='Title',
            new_name='title',
        ),
    ]
